# Generated by Django 4.2 on 2023-05-01 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blockchain', '0005_alter_block_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blockchain.transaction'),
        ),
    ]
