# Generated by Django 4.2 on 2023-05-09 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0009_greener_wallet'),
        ('Blockchain', '0007_alter_block_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='GreenersAccount.greener'),
        ),
    ]
