# Generated by Django 4.2 on 2023-05-09 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompostersAccount', '0002_composter_groups_composter_is_superuser_and_more'),
        ('Blockchain', '0008_alter_transaction_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompostersAccount.composter'),
        ),
    ]
