# Generated by Django 4.2 on 2023-04-30 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0006_delete_compost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manure', models.FloatField()),
                ('brown_material', models.FloatField()),
                ('green_material', models.FloatField()),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenersAccount.greener')),
            ],
        ),
    ]
