# Generated by Django 4.2 on 2023-04-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0007_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
