# Generated by Django 4.2 on 2023-04-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0008_offer_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='greener',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
