# Generated by Django 4.2 on 2023-05-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0010_greenernotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='greener',
            name='ComposterStatus',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted')], default='waiting', max_length=50),
        ),
    ]
