# Generated by Django 4.2 on 2023-06-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0012_auto_20230602_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenernotifications',
            name='IsRead',
        ),
        migrations.AlterField(
            model_name='offer',
            name='Status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
